variable "vault_auth_type" {
  type        = string
  description = "(Optional) Type of auth method that will be created. Defaults to kubernetes"
  default     = "kubernetes"
}

variable "vault_auth_path" {
  type        = string
  description = "(Optional) Path to mount the auth method. Defaults to kubernetes"
  default     = "kubernetes"
}

variable "kubernetes_api_url" {
  type        = string
  description = "(Required) URL for Vault to use when reaching the Kubernetes API"
}

variable "max_lease_ttl" {
  type        = string
  description = "(Optional) Maximum TTL that will be allowed for leases associated with this auth method"
  default     = "2h"
}

variable "default_lease_ttl" {
  type        = string
  description = "(Optional) Default TTL associated with the leases generated by this auth method"
  default     = "1h"
}

variable "vault_k8s_namespace" {
  type        = string
  description = "(Optional) Namespace where Vault was be deployed in the Kubernetes cluster.Defaults to vault"
  default     = "vault"
}

variable "vault_svc_account_name" {
  type        = string
  description = "(Optional) Service Account that was created via the Helm chart in the Kubernetes cluster. Defaults to vault"
  default     = "vault"
}

variable "vault_namespace" {
  type        = string
  description = "(Optional) Namespace in Vault where the authentication method will be configured. Defaults to admin"
  default     = "admin"
}
